<!-- SCRIPTS -->
<?php if(false && $_ENV['SERVER_ENVIRONMENT']==="prod"){ ?>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/what-input/5.2.12/what-input.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.7.5/js/foundation.min.js" crossorigin="anonymous"></script>
<?php }else{ ?>
    <script src="<?= HTML_JS ?>/vendor/jquery-3.6.3.min.js" crossorigin="anonymous"></script>
    <script src="<?= HTML_JS ?>/vendor/what-input-5.2.12.min.js" crossorigin="anonymous"></script>
    <script src="<?= HTML_JS ?>/vendor/foundation-6.7.5.min.js" crossorigin="anonymous"></script>
    <script src="<?= HTML_JS ?>/main.js" crossorigin="anonymous"></script>
<?php } ?>