<? /*
<!-- OPEN GRAPH -->
<!--    <meta property="og:site_name" content="<?= CONFIGS::GET("APP", 'tilte'); ?>" />-->
<!--    <meta property="og:title" content="<?= CONFIGS::GET("APP", 'tilte'); ?>" />-->
<!--    <meta property="og:description" content="<?= CONFIGS::GET("APP", 'description'); ?>" />-->
<!--    <meta property="og:type" content="website" />-->
<!--    <meta property="og:url" content="https://address.com" />-->
<!--    <meta property="og:image" content="http://address.com/logo.png" />-->
<!--    <meta property="og:image:secure_url" content="https://address.com/logo.png" />-->

*/