<!-- STYLE -->
<?php if(false && $_ENV['SERVER_ENVIRONMENT']==="prod"){ ?>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.7.5/css/foundation.min.css" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="<?= HTML_CSS ?>/forms/1.0.css" crossorigin="anonymous">
<?php }else{ ?>
    <link rel="stylesheet" type="text/css" href="<?= HTML_CSS ?>/vendor/normalize-8.0.1.min.css" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="<?= HTML_CSS ?>/vendor/foundation-6.7.5.min.css" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="<?= HTML_CSS ?>/forms/1.0.css" crossorigin="anonymous">
<?php } ?>