<? /*
<!-- TWITTER -->
<!--    <meta name="twitter:card" content="summary">-->
<!--    <meta name="twitter:image" content="https://address.com/logo.png">-->
<!--    <meta name="twitter:site" content="@twitterId">-->
<!--    <meta name="twitter:title" content="<?= CONFIGS::GET("APP", 'title'); ?>">-->
<!--    <meta name="twitter:description" content="<?= CONFIGS::GET("APP", 'description'); ?>">-->

*/