<footer>
    <div class="grid-container">
        <div class="grid-x grid-margin-x">
    
            <div class="to-top cell small-12">
                <a href='#'><i class='fi-arrow-up'></i>Top</a>
            </div>
            
            <div class="cell small-12 medium-6">
                <ul>
                    <li><a href='<?= HTML_ROOT ?>/path/to/page'>Link</a></li>
                    <li><a href='<?= HTML_ROOT ?>/path/to/page'>Link</a></li>
                </ul>
            </div>
            
            <div class="logo cell small-12 medium-5">
                <a href='<?= HTML_ROOT ?>/'><img src="<?= HTML_IMG ?>/logos/logo.png" alt="<?= CONFIGS::GET("APP", 'title'); ?>" width="500" height="200"></a>
            </div>
            
        </div>
    </div>
</footer>