<?php if(false && $_ENV['SERVER_ENVIRONMENT']==="prod"){ ?>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/what-input/5.2.12/what-input.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.7.5/js/foundation.min.js" crossorigin="anonymous"></script>
<?php }else{ ?>
    <script src="/js/vendor/jquery-3.6.3.min.js" crossorigin="anonymous"></script>
    <script src="/js/vendor/what-input-5.2.12.min.js" crossorigin="anonymous"></script>
    <script src="/js/vendor/foundation-6.7.5.min.js" crossorigin="anonymous"></script>
<?php } ?>
    <script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "Organization",
        "name": "<?= CONFIGS::GET("APP", 'tilte'); ?>",
        "url": "http://<?= CONFIGS::GET("APP", 'domain'); ?>",
        "address": "",
        "sameAs": [
            "https://<?= CONFIGS::GET("APP", 'facebook-url'); ?>"
        ]
    }
    </script>
    <script>
        $(document).foundation();
    </script>
