        </div>
    </div>
</section>

<footer>
    <div class="grid-container">
        <div class="grid-x grid-margin-x">
    
            <div class="to-top cell small-12">
                <a href='#'><i class='fi-arrow-up'></i>Topo</a>
            </div>
            
            <div class="cell small-12 medium-6">
                <ul>
                    <li><a href='/Documentos/TermosDeUso'>Termos de Uso</a></li>
                    <li><a href='/Documentos/PoliticasDePrivacidade'>Politica de Privacidade</a></li>
                </ul>
            </div>
            
            <div class="logo cell small-12 medium-5">
                <a href='/'><img src="/img/logos/arprev-rectangle-pink-background.png" alt="AR Prev" width="500" height="200"></a>
            </div>
            
<?php if(false){ ?>
            <div class="whats-app cell small-6">
                <a target="_blank" rel="noopener" href="//api.whatsapp.com/send?phone=5511978549551"><img src="/img/logos/whatsapp-65x65.png" alt="WhatsApp" width="65" height="65"></a>
            </div>
<?php } ?>
        </div>
    </div>
</footer>
