<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <link rel="canonical" href="<?= $_SERVER['REQUEST_SCHEME']; ?>://<?= $_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'] ?>">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><?= CONFIGS::GET("APP", 'title'); ?></title>
    <meta name="description" content="<?= CONFIGS::GET("APP", 'description'); ?>">

    <?= $this->partial('_head/google-tag-manager'); ?>
    <?= $this->partial('_head/fonts'); ?>
    <?= $this->partial('_head/style'); ?>
    <?= $this->partial('_head/open-graph'); ?>
    <?= $this->partial('_head/twitter'); ?>
    <?= $this->partial('_head/favicon'); ?>
</head>