<?php if(false){ ?>
<header>
    <div class="grid-container">
        <div class="grid-x grid-margin-x">
            <!-- LOGO -->
            <div class="logo cell small-12">
                <h1><a href='/'><img src="/img/logos/arprev-rectangle-transparent-1000x300.png" alt="AR&nbsp;Prev" width="167" height="50"></a></h1>
            </div>
        </div>
    </div>
</header>

<?php } ?>
<section class="grid-container">
    <div class="grid-x grid-margin-x">
        <div class="cell small-12">
