#!/bin/sh
set -e

forceRun=$1;

echo_h1 CONTAINER - START;
if [[ -f "/run/container/start-done" ]] && [[ "${forceRun}" == '' ]]; then
    echo "[===]";
else
    fsSetup_echoHeader h2;
    fsSetup_clearErrors;
    # Container
    fsSetup 777 root root ${ROOT_DATA}/;
    fsSetup 777 root root ${ROOT_LOGS}/;
    # OS
    fsSetup 777 root root ${OS_DATA}/;
    fsSetup 777 root root ${OS_LOGS}/;
    # App
    fsSetup 777 root root ${APP_ROOT}/;
    # Container
    #fsSetup 777 root root /run/container/start-done;

    echo_h2 LOGS - OS;
    if [[ ! -e "${OS_LOGS}/logs-link" ]]; then
        ln -s "/var/log" "${OS_LOGS}/logs-link"
        chmod 777 "${OS_LOGS}/logs-link"
    fi

    echo_h2;
    if [ $(fsSetup_hasErrors) == '1' ]; then
        echo "[ERROR]";
        exit 1;
    fi
fi
